# Generated by Django 5.2.3 on 2025-06-18 08:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('reddit_username', models.CharField(db_index=True, max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead Profile',
                'verbose_name_plural': 'Lead Profiles',
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reddit_post_id', models.CharField(max_length=20, unique=True)),
                ('post_url', models.URLField(unique=True)),
                ('post_title', models.CharField(max_length=300)),
                ('post_category', models.CharField(blank=True, max_length=100, null=True)),
                ('subreddit', models.CharField(db_index=True, max_length=100)),
                ('post_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('post_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Reddit Post',
                'verbose_name_plural': 'Reddit Posts',
                'db_table': 'posts',
                'ordering': ['-post_time'],
            },
        ),
    ]
